"""Various defaults for challenges, games etc."""


DEFAULT_ONSK8S_DURATION = '2'
DEFAULT_OFFSK8S_DURATION = '1'
DEFAULT_CHALLENGE_DURATION = '0.75'
DEFAULT_SANCTIONED_DURATION = '1.5'
GAME_CAP = 20

DEFAULT_REG_CAP = 60
DEFAULT_AUD_CAP = 10

MAX_CAPTAIN_LIMIT = 2
CLOSE_CHAL_SUB_AT = 250
