"""
Django settings for rcreg_project project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cih+_v$pnesdlbfjzo(o-m7=vij9lans81_$#oe&gt+o1cez=+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['rcregsite.pythonanywhere.com']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',# https://django-registration-redux.readthedocs.org/en/latest/index.html
    'con_event',
    'scheduler',
    'datetimewidget',#https://github.com/asaglimbeni/django-datetime-widget
    'import_export',#https://readthedocs.org/projects/django-import-export/
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
)

ROOT_URLCONF = 'rcreg_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            #below, testing out the idea of keeping templates in app dir instead of central template dir
            #os.path.join(BASE_DIR, 'django-registration/registration/templates'),
            #os.path.join(BASE_DIR, 'admin'),
            #os.path.join(BASE_DIR, 'templates/admin'),
            os.path.join(BASE_DIR, 'registration/templates'),
            os.path.join(BASE_DIR, 'con_event/templates'),
            os.path.join(BASE_DIR, 'scheduler/templates'),
            ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'rcreg_project.custom_processors.unaccepted_challenge_notifications',
                # 'rcreg_project.custom_processors.pending_challenge_notifications',
                'rcreg_project.custom_processors.all_challenge_notifications',
                'rcreg_project.custom_processors.get_site_admin_email',
                'rcreg_project.custom_processors.get_rc_admin_email',
            ],
        },
    },
]

WSGI_APPLICATION = 'rcreg_project.wsgi.application'

THis is the development DB on my Macbook AIR
DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql',
        #'NAME': 'rcreg2016',
        'NAME': 'rcregsite$default',#trying to match name, w/ pythonanywhere, see if it works
        'USER': 'root',
        'PASSWORD': 'mice4rice',
        #'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        #'PORT': '3306',
        #'PORT': '', #blank so default is selected
        }
}


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' #? http://stackoverflow.com/questions/6782732/no-connection-could-be-made-because-the-target-machine-actively-refused-it-djan
#read this lateR: https://docs.djangoproject.com/en/1.7/topics/email/
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
ADMINS = (
  ('Dahmer', 'mdaizovi@gmail.com'),('Pho', 'rcregsite@gmail.com'),
)
EMAIL_SUBJECT_PREFIX="RC Reg Site to Admins: "

#I made up this variables
CUSTOM_SITE_ADMIN_EMAIL="rcregsite@gmail.com"
RC_GENERAL_ADMIN_EMAIL="rollercon@gmail.com"
from django.contrib.auth.models import Group
# #i did this bc i accidentally had BIG_BOSS_GROUP_NAME written all over not realizing it was a string and not an object.
# BIG_BOSS_GROUP_NAME,c1=Group.objects.get_or_create(name="Khaleesi")
# LOWER_BOSS_GROUP_NAME,c2=Group.objects.get_or_create(name="Blood Rider")
have to make none for initial migrations
BIG_BOSS_GROUP_NAME=None
LOWER_BOSS_GROUP_NAME=None

#GENERAL_DISPLAY_EMAIL="planning@rollercon.com"#This is a setting I made up
from django.core.mail import send_mail,EmailMessage
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'rcregsite@gmail.com'
EMAIL_HOST_PASSWORD = '@$$p3nn13$'
EMAIL_PORT = 587
#ACCOUNT_EMAIL_VERIFICATION = 'none'
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER


ACCOUNT_ACTIVATION_DAYS = 300 # One-week activation window; you may, of course, use a different value.
REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.
REGISTRATION_EMAIL_HTML = False #Optional. If this is False, registration emails will be send in plain text. If this is True, emails will be sent as HTML. Defaults to True.
LOGIN_REDIRECT_URL = '/' #make this a profile page later
REGISTRATION_OPEN=False #will this still let me mke new users? all i want to do is make it impossible for randoms to register themelves.
#LOGIN_URL = '/accounts/login/' #seems redundant

#nothing works when i change these
#INCLUDE_AUTH_URLS=False #? https://django-registration-redux.readthedocs.org/en/latest/default-backend.html
#INCLUDE_REGISTER_URL=False #This is important so users can't register themselves, a User must be created after they've paid for a pass


SITE_ID=1

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'#consisent w/ both San Diego base of operations and LV action

USE_I18N = True

USE_L10N = True

USE_TZ = False #this needs to be fale, else it will be UTC #http://stackoverflow.com/questions/32913021/python-django-time-zone-conversion-incorrect-time-for-us-pacific-time-zone


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_PATH = os.path.join(BASE_DIR,'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (STATIC_PATH,'css', 'js', 'images', 'media','font-awesome','fonts','fontello')
#was hoping this would fix my admin clock image issue, but it didn't #
#ADMIN_MEDIA_PREFIX = '/static/admin/'


# from: http://ianalexandr.com/blog/getting-started-with-django-logging-in-5-minutes.html
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             'datefmt' : "%d/%b/%Y %H:%M:%S"
#         },
#         'simple': {
#             'format': '%(levelname)s %(message)s'
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': 'mysite.log',
#             'formatter': 'verbose'
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers':['file'],
#             'propagate': True,
#             'level':'DEBUG',
#         },
#         'rcreg_project': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#         },
#     }
# }

BPT_Affiliate_ID='1476741'
BPT_Developer_ID= 't3iip9rK2C'
##GOOGLE APP ENGINE
GOOGLE_API_KEY='AIzaSyAI1ul8NSVqb5gOdzDCAnTRj53U6n2pUUc'
OAuth_CLIENT_ID='1020807546728-apuqfp2t2n6f0evp3msqluoh8he6621s.apps.googleusercontent.com'
OAuth_Client_Secret='G9WFQZ-Ivz2Q8mB57F0uer2S'

OAuth_CLIENT_ID_CALENDAR='1020807546728-374a38hbvuaqhrorhf1ojumtajafbllv.apps.googleusercontent.com'
OAuth_Client_Secret_CALENDAR='4WsPYUDnQhTJYOGGxP7931Xk'
